apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: simple-fluentbit
  namespace: default
spec:
  selector:
    matchLabels:
      app: simple-fluentbit
  template:
    metadata:
      labels:
        app: simple-fluentbit
    spec:
      containers:
      - name: fluentbit
        image: fluent/fluent-bit:1.9
        volumeMounts:
        - name: config
          mountPath: /fluent-bit/etc/
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: simple-fluentbit-config
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers