apiVersion: remediation.kuberescue.io/v1alpha1
kind: LogRemediation
metadata:
  name: test3-service-cascade-remediation
spec:
  sources:
  - type: deployment
    selector:
      app: test3-service-cascade-app
  elasticsearchConfig:
    host: elasticsearch.default.svc.cluster.local
    port: 9200
    index: kubernetes-logs
  fluentbitConfig:
    bufferSize: "10MB"
    flushInterval: 1
  remediationRules:
  - errorPattern: "CRITICAL_SERVICE_FAILURE"
    action: restart
    cooldownPeriod: 60
  - errorPattern: "PERSISTENT_SERVICE_FAILURE"
    action: restart
    cooldownPeriod: 120
  - errorPattern: "SYSTEM_WIDE_FAILURE"
    action: restart
    cooldownPeriod: 180