apiVersion: remediation.kuberescue.io/v1alpha1
kind: LogRemediation
metadata:
  name: test2-memory-leak-remediation
spec:
  sources:
  - type: deployment
    selector:
      app: test2-memory-leak-app
  elasticsearchConfig:
    host: elasticsearch.default.svc.cluster.local
    port: 9200
    index: kubernetes-logs
  fluentbitConfig:
    bufferSize: "10MB"
    flushInterval: 1
  remediationRules:
  - errorPattern: "High memory usage detected"
    action: scale
    cooldownPeriod: 180
  - errorPattern: "CRITICAL: Memory threshold exceeded"
    action: restart
    cooldownPeriod: 300