apiVersion: remediation.kuberescue.io/v1alpha1
kind: LogRemediation
metadata:
  name: test1-db-error-remediation
spec:
  sources:
  - type: deployment
    selector:
      app: test1-db-error-app
  elasticsearchConfig:
    host: elasticsearch.default.svc.cluster.local
    port: 9200
    index: kubernetes-logs
  fluentbitConfig:
    bufferSize: "10MB"
    flushInterval: 1
  remediationRules:
  - errorPattern: "CRITICAL_DB_CONNECTION_FAILED"
    action: restart
    cooldownPeriod: 60