apiVersion: apps/v1
kind: Deployment
metadata:
  name: test1-db-error-app
  labels:
    app: test1-db-error-app
    test: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test1-db-error-app
  template:
    metadata:
      labels:
        app: test1-db-error-app
    spec:
      containers:
      - name: error-generator
        image: busybox
        command:
        - /bin/sh
        - -c
        - |
          while true; do 
            echo "$(date) [INFO] Normal operation"
            sleep 5
            echo "$(date) [ERROR] CRITICAL_DB_CONNECTION_FAILED: Cannot connect to database"
            sleep 10
          done