apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: test-pagerduty
  namespace: monitoring
spec:
  groups:
  - name: test
    rules:
    - alert: TestPagerDutyIntegration
      expr: vector(1)
      for: 10s
      labels:
        severity: critical
        application: test
      annotations:
        summary: "Test PagerDuty Integration"
        description: "This is a test alert to verify PagerDuty integration. You can ignore this."