apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-prometheus-kube-prometheus-alertmanager
  namespace: monitoring
stringData:
  alertmanager.yaml: |
    global:
      resolve_timeout: 5m

    route:
      group_by: ['alertname']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 4h
      receiver: 'pagerduty'
      
    receivers:
    - name: 'pagerduty'
      pagerduty_configs:
      - service_key: 'fa95cf2f01334808d1c76f0b6fd66f3e'
        description: '{{ .CommonLabels.alertname }}'
        details:
          severity: '{{ .CommonLabels.severity }}'
          summary: '{{ .CommonAnnotations.summary }}'
          description: '{{ .CommonAnnotations.description }}'
        client: 'Prometheus'
        client_url: 'http://prometheus-kube-prometheus-prometheus.monitoring:9090'
        send_resolved: true
type: Opaque