apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: kuberescue-alerts
  namespace: monitoring
  labels:
    prometheus: kube-prometheus 
    release: prometheus 
spec:
  groups:
  - name: kuberescue.alerts
    rules:
    - alert: HighErrorRate
      expr: sum(rate(kuberescue_error_pattern_occurrences_total[5m])) by (application) > 0.3
      for: 3m
      labels:
        severity: critical
        application: "{{ $labels.application }}"
      annotations:
        summary: "High error rate for {{ $labels.application }}"
        description: "Application {{ $labels.application }} has a high error rate ({{ $value }} errors/sec)"