apiVersion: remediation.kuberescue.io/v1alpha1
kind: LogRemediation
metadata:
  name: test5-intermittent-failure-remediation
spec:
  sources:
    - type: deployment
      selector:
        app: test5-intermittent-failure-app
  elasticsearchConfig:
    host: elasticsearch.default.svc.cluster.local
    port: 9200
    index: kubernetes-logs
  fluentbitConfig:
    bufferSize: "10MB"
    flushInterval: 1
  remediationRules:
    - errorPattern: "INTERMITTENT_TIMEOUT"
      action: restart
      cooldownPeriod: 120  
    - errorPattern: "INTERMITTENT_CONNECTION_DROP"
      action: restart
      cooldownPeriod: 180
    - errorPattern: "CRITICAL_INTERMITTENT_FAILURE"
      action: scale
      cooldownPeriod: 300
    - errorPattern: "Application processing request normally"
      action: recovery
      cooldownPeriod: 600