---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - remediation.kuberescue.io
  resources:
  - logremediations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - remediation.kuberescue.io
  resources:
  - logremediations/finalizers
  verbs:
  - update
- apiGroups:
  - remediation.kuberescue.io
  resources:
  - logremediations/status
  verbs:
  - get
  - patch
  - update
