//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElasticsearchConfig) DeepCopyInto(out *ElasticsearchConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElasticsearchConfig.
func (in *ElasticsearchConfig) DeepCopy() *ElasticsearchConfig {
	if in == nil {
		return nil
	}
	out := new(ElasticsearchConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FluentbitConfig) DeepCopyInto(out *FluentbitConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FluentbitConfig.
func (in *FluentbitConfig) DeepCopy() *FluentbitConfig {
	if in == nil {
		return nil
	}
	out := new(FluentbitConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogRemediation) DeepCopyInto(out *LogRemediation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogRemediation.
func (in *LogRemediation) DeepCopy() *LogRemediation {
	if in == nil {
		return nil
	}
	out := new(LogRemediation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LogRemediation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogRemediationList) DeepCopyInto(out *LogRemediationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LogRemediation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogRemediationList.
func (in *LogRemediationList) DeepCopy() *LogRemediationList {
	if in == nil {
		return nil
	}
	out := new(LogRemediationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LogRemediationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogRemediationSpec) DeepCopyInto(out *LogRemediationSpec) {
	*out = *in
	if in.Sources != nil {
		in, out := &in.Sources, &out.Sources
		*out = make([]LogSource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.ElasticsearchConfig = in.ElasticsearchConfig
	if in.FluentbitConfig != nil {
		in, out := &in.FluentbitConfig, &out.FluentbitConfig
		*out = new(FluentbitConfig)
		**out = **in
	}
	if in.RemediationRules != nil {
		in, out := &in.RemediationRules, &out.RemediationRules
		*out = make([]RemediationRule, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogRemediationSpec.
func (in *LogRemediationSpec) DeepCopy() *LogRemediationSpec {
	if in == nil {
		return nil
	}
	out := new(LogRemediationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogRemediationStatus) DeepCopyInto(out *LogRemediationStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.FluentbitPods != nil {
		in, out := &in.FluentbitPods, &out.FluentbitPods
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.LastConfigured != nil {
		in, out := &in.LastConfigured, &out.LastConfigured
		*out = (*in).DeepCopy()
	}
	if in.RemediationHistory != nil {
		in, out := &in.RemediationHistory, &out.RemediationHistory
		*out = make([]RemediationHistoryEntry, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogRemediationStatus.
func (in *LogRemediationStatus) DeepCopy() *LogRemediationStatus {
	if in == nil {
		return nil
	}
	out := new(LogRemediationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogSource) DeepCopyInto(out *LogSource) {
	*out = *in
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogSource.
func (in *LogSource) DeepCopy() *LogSource {
	if in == nil {
		return nil
	}
	out := new(LogSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemediationHistoryEntry) DeepCopyInto(out *RemediationHistoryEntry) {
	*out = *in
	in.Timestamp.DeepCopyInto(&out.Timestamp)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemediationHistoryEntry.
func (in *RemediationHistoryEntry) DeepCopy() *RemediationHistoryEntry {
	if in == nil {
		return nil
	}
	out := new(RemediationHistoryEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemediationRule) DeepCopyInto(out *RemediationRule) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemediationRule.
func (in *RemediationRule) DeepCopy() *RemediationRule {
	if in == nil {
		return nil
	}
	out := new(RemediationRule)
	in.DeepCopyInto(out)
	return out
}
