apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: main
  namespace: monitoring
spec:
  replicas: 1
  configSecret: alertmanager-kuberescue  # This should point to your secret
  secrets:
    - pagerduty-secrets
  configMaps: []  # If you have any configMaps to include
  alertmanagerConfigSelector: {}  # This is important - make it empty to disable default config
  alertmanagerConfigNamespaceSelector: {}  # This is important - make it empty to disable default config