# alertmanager-config.yaml (safe to commit)
apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-kuberescue
  namespace: monitoring
  labels:
    app: prometheus
stringData:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m
      pagerduty_url: 'https://events.eu.pagerduty.com/v2/enqueue'

    route:
      group_by: ['alertname', 'severity', 'application']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 4h
      receiver: 'pagerduty-warnings'
      routes:
      - match:
          severity: critical
        receiver: 'pagerduty-critical'
      - match:
          severity: warning
        receiver: 'pagerduty-warnings'

    receivers:
    - name: 'pagerduty-critical'
      pagerduty_configs:
      - service_key_file: /etc/alertmanager/secrets/pagerduty/service-key
        description: 'CRITICAL: {{ .GroupLabels.alertname }}'
        details:
          application: '{{ .CommonLabels.application }}'
          alertname: '{{ .GroupLabels.alertname }}'
          summary: '{{ .CommonAnnotations.summary }}'
          description: '{{ .CommonAnnotations.description }}'
        severity: critical
        class: 'kuberescue-critical'
        component: '{{ .CommonLabels.application }}'
        group: 'kuberescue'
        client: 'KubeRescue AlertManager'
        client_url: '{{ if .CommonAnnotations.dashboard_url }}{{ .CommonAnnotations.dashboard_url }}{{ end }}'
        send_resolved: true

    - name: 'pagerduty-warnings'
      pagerduty_configs:
      - service_key_file: /etc/alertmanager/secrets/pagerduty/service-key
        description: 'WARNING: {{ .GroupLabels.alertname }}'
        details:
          application: '{{ .CommonLabels.application }}'
          alertname: '{{ .GroupLabels.alertname }}'
          summary: '{{ .CommonAnnotations.summary }}'
          description: '{{ .CommonAnnotations.description }}'
        severity: warning
        class: 'kuberescue-warning'
        component: '{{ .CommonLabels.application }}'
        group: 'kuberescue'
        client: 'KubeRescue AlertManager'
        client_url: '{{ if .CommonAnnotations.dashboard_url }}{{ .CommonAnnotations.dashboard_url }}{{ end }}'
        send_resolved: true
type: Opaque